"""Schemas package."""

from app.schemas.auth import (
    UserRegisterRequest,
    UserLoginRequest,
    TokenResponse,
    UserResponse,
    UserProfileResponse,
)
from app.schemas.resume import (
    PersonalInformationSchema,
    ResumeSectionSchema,
    ResumeProjectSchema,
    ResumeExperienceSchema,
    ResumeCertificationSchema,
    ResumeSummaryResponse,
    StructuredResumeResponse,
)
from app.schemas.skill import (
    SkillSchema,
    SkillAliasSchema,
    SkillRelationshipSchema,
    ExtractedSkillMatch,
    ResumeSkillsResponse,
)
from app.schemas.job import (
    JobSectionSchema,
    JobRequirementSchema,
    JobSkillSchema,
    JobExperienceRequirementSchema,
    JobEducationRequirementSchema,
    JobCertificationSchema,
    JobCreatePastedSchema,
    JobSummaryResponse,
    StructuredJobResponse,
)
from app.schemas.matching import (
    MatchRequestSchema,
    SkillMatchSchema,
    SkillGapSchema,
    ScoreBreakdownSchema,
    StructuredAlignmentSchema,
    ExplainabilitySummarySchema,
    MatchAnalysisResponse,
    ResumeSkillGapsResponse,
)
from app.schemas.career import (
    OccupationSkillSchema,
    OccupationResponseSchema,
    CareerCompatibilityComponentSchema,
    CareerRoleMatchSchema,
    CareerCompatibilityResponseSchema,
)
from app.schemas.learning import (
    LearningResourceSchema,
    LearningPathItemSchema,
    LearningStageSchema,
    LearningPathGraphNode,
    LearningPathGraphEdge,
    LearningPathGraphSchema,
    LearningPathCreateRequest,
    ItemProgressUpdateRequest,
    LearningPathResponseSchema,
)

from app.schemas.dashboard import (
    ResumeVersionSummary,
    ResumeVersionComparisonResponse,
    SkillHistoryItem,
    SkillHistoryResponse,
    ScoreHistoryItem,
    LearningProgressOverview,
    DashboardOverviewResponse,
)

__all__ = [
    "UserRegisterRequest",
    "UserLoginRequest",
    "TokenResponse",
    "UserResponse",
    "UserProfileResponse",
    "PersonalInformationSchema",
    "ResumeSectionSchema",
    "ResumeProjectSchema",
    "ResumeExperienceSchema",
    "ResumeCertificationSchema",
    "ResumeSummaryResponse",
    "StructuredResumeResponse",
    "SkillSchema",
    "SkillAliasSchema",
    "SkillRelationshipSchema",
    "ExtractedSkillMatch",
    "ResumeSkillsResponse",
    "JobSectionSchema",
    "JobRequirementSchema",
    "JobSkillSchema",
    "JobExperienceRequirementSchema",
    "JobEducationRequirementSchema",
    "JobCertificationSchema",
    "JobCreatePastedSchema",
    "JobSummaryResponse",
    "StructuredJobResponse",
    "MatchRequestSchema",
    "SkillMatchSchema",
    "SkillGapSchema",
    "ScoreBreakdownSchema",
    "StructuredAlignmentSchema",
    "ExplainabilitySummarySchema",
    "MatchAnalysisResponse",
    "ResumeSkillGapsResponse",
    "OccupationSkillSchema",
    "OccupationResponseSchema",
    "CareerCompatibilityComponentSchema",
    "CareerRoleMatchSchema",
    "CareerCompatibilityResponseSchema",
    "LearningResourceSchema",
    "LearningPathItemSchema",
    "LearningStageSchema",
    "LearningPathGraphNode",
    "LearningPathGraphEdge",
    "LearningPathGraphSchema",
    "LearningPathCreateRequest",
    "ItemProgressUpdateRequest",
    "LearningPathResponseSchema",
    "ResumeVersionSummary",
    "ResumeVersionComparisonResponse",
    "SkillHistoryItem",
    "SkillHistoryResponse",
    "ScoreHistoryItem",
    "LearningProgressOverview",
    "DashboardOverviewResponse",
]
